kernel:
  image: linuxkit/kernel:4.9.34
  cmdline: "console=ttyS0 page_poison=1"
init:
  - linuxkit/init:817099ace2d56ea2d20c7702ab8e1a8abc7d89fd
  - linuxkit/runc:59c40661f2174ca6752d73086b91d63eeb98d021
  - linuxkit/containerd:0dab9a4e2b9aa7f034873881a08890fd40b2755d
  - linuxkit/ca-certificates:6003d7e78387f1fbb35bf1d1af300120be97f94b
  - samoht/fdd
onboot:
  - name: sysctl
    image: linuxkit/sysctl:f8a06fea01bfcb322e913213e22d35790168ed01
services:
  - name: getty
    image: linuxkit/getty:9b8e6b510b49da196a1e412aa95f364e3dd16576
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:e35c1c671a9d35dbc42b83b620563ce472f8effb
  - name: dhcpcd
    image: linuxkit/dhcpcd:a58543e8b40a29b3cd0c5d1e42ce21b71a8abcef
files:
  - path: etc/init.d/020-fdd-init
    mode: "0700"
    contents: |
      #!/bin/sh
      /bin/fdd init -vv -s /run/fdd.sock
  - path: etc/init.d/030-fdd-share
    mode: "0700"
    contents: |
      #!/bin/sh
      /bin/fdd share -vv -s /run/fdd.sock /tmp/channel-net-eng &&
      /bin/fdd share -vv -s /run/fdd.sock /tmp/channel-conf-net &&
      /bin/fdd share -vv -s /run/fdd.sock /tmp/channel-conf-act
trust:
  org:
    - linuxkit
