kernel:
  image: linuxkit/kernel:4.9.34
  cmdline: "console=ttyS0 page_poison=1"
init:
  - linuxkit/init:5251073a3d3e52881bf2697f7dfabac6eedfd569
  - linuxkit/runc:49628804b3a39b0a0cfab046dd80b76a4fd87b5a
  - linuxkit/containerd:c35f10fb8127841b4eb82ddfcebd5d5a54bad0e7
  - linuxkit/ca-certificates:945ac3f0c1a31535d37ff77003fc30dbd71da6bb
  - samoht/fdd
onboot:
  - name: sysctl
    image: linuxkit/sysctl:7c0059d1ad7d86127d990474b6e5f17297c07bf5
services:
  - name: getty
    image: linuxkit/getty:d421b06d0a1ae118e2af025cb7a3637f808a755b
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:97136824ad06ba2cc17c086d30f60c7f93b56f72
  - name: dhcpcd
    image: linuxkit/dhcpcd:fc2b5bf40b13df746ee66f354672bf687a540ce8
files:
  - path: etc/init.d/020-fdd-init
    mode: "0700"
    contents: |
      #!/bin/sh
      /bin/fdd init -vv -s /run/fdd.sock
  - path: etc/init.d/030-fdd-share
    mode: "0700"
    contents: |
      #!/bin/sh
      /bin/fdd share -vv -s /run/fdd.sock /tmp/channel-net-eng &&
      /bin/fdd share -vv -s /run/fdd.sock /tmp/channel-conf-net &&
      /bin/fdd share -vv -s /run/fdd.sock /tmp/channel-conf-act
trust:
  org:
    - linuxkit
