kernel:
  image: linuxkit/kernel:4.9.34
  cmdline: "console=ttyS0 page_poison=1"
init:
  - linuxkit/init:ad37cb61355b08cf481c54b07612b5206be6254d
  - linuxkit/runc:8c00a7c58393f0cfcab81ac4171c00bcaec6b962
  - linuxkit/containerd:26f04b0b57e3d21bfb36732b5c6ebe8f08c6705b
  - linuxkit/ca-certificates:a37095d3d576815fdefe76a28444c68cd9eac8fe
  - samoht/fdd
onboot:
  - name: sysctl
    image: linuxkit/sysctl:984bff0476b059ae86b4c3e7c15f93f72a5d0a57
services:
  - name: getty
    image: linuxkit/getty:97d0743bc3baa349dc96809b58f8584c5896928a
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:f46ebc10118bac79f68607c3c3308f0da8d9bde3
  - name: dhcpcd
    image: linuxkit/dhcpcd:0060977dc2cd15eb242c21888fad240f96ec7308
files:
  - path: etc/init.d/020-fdd-init
    mode: "0700"
    contents: |
      #!/bin/sh
      /bin/fdd init -vv -s /run/fdd.sock
  - path: etc/init.d/030-fdd-share
    mode: "0700"
    contents: |
      #!/bin/sh
      /bin/fdd share -vv -s /run/fdd.sock /tmp/channel-net-eng &&
      /bin/fdd share -vv -s /run/fdd.sock /tmp/channel-conf-net &&
      /bin/fdd share -vv -s /run/fdd.sock /tmp/channel-conf-act
trust:
  org:
    - linuxkit
