kernel:
  image: linuxkit/kernel:5.10.104
  cmdline: "console=ttyS0 page_poison=1"
init:
  - linuxkit/init:31dcd928602e39ee752843ebcf6c35cbae73c883
  - linuxkit/runc:7ecf2e5253905855fb554b072d42903f7829c8b6
  - linuxkit/containerd:f645aa2f8aa58023149d7766725039572a2ebeb5
onboot:
  - name: sysctl
    image: linuxkit/sysctl:2f575c3d127824eb8d059673c538c440d22f19f5
  - name: dhcp-client
    image: miragesdk/dhcp-client:22aa9d527820534295a8cd59901c0c5197af6585
    net: host
    capabilities:
     - CAP_NET_ADMIN # to bring eth0 up
     - CAP_NET_RAW   # to read /dev/eth0
     - CAP_SYS_ADMIN # for runc (unshare)
     - CAP_SETGID    # for runc (setns)
    mounts: # for runc
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /var/run/dhcp-client:/data
     - /usr/bin/runc:/usr/bin/runc # for runc
     - /run/runc:/run/runc         # for runc
     - /sbin:/sbin   # for ifconfig
     - /bin:/bin     # for ifconfig
     - /lib:/lib     # for ifconfig
services:
  - name: sshd
    image: linuxkit/sshd:d7286e080dc56a2d5718d20e51efbe32123f83ba
  - name: getty
    image: linuxkit/getty:ccac1189f78ff466b76d097a0b7b7236ea54de84
    env:
     - INSECURE=true
files:
  - path: var/run/dhcp-client/README
    contents: 'data for dhcp-client'
  - path: root/.ssh/authorized_keys
    contents: '#your SSH key here'
