kernel:
  image: linuxkit/kernel:6.6.13
  cmdline: "console=ttyS0 page_poison=1"
init:
  - linuxkit/init:9eabfb21879d4a3c9534f0c4e9a764919423e8a5
  - linuxkit/runc:6062483d748609d505f2bcde4e52ee64a3329f5f
  - linuxkit/containerd:39301e7312f13eedf19bd5d5551af7b37001d435
onboot:
  - name: sysctl
    image: linuxkit/sysctl:5a374e4bf3e5a7deeacff6571d0f30f7ea8f56db
  - name: dhcp-client
    image: miragesdk/dhcp-client:22aa9d527820534295a8cd59901c0c5197af6585
    net: host
    capabilities:
     - CAP_NET_ADMIN # to bring eth0 up
     - CAP_NET_RAW   # to read /dev/eth0
     - CAP_SYS_ADMIN # for runc (unshare)
     - CAP_SETGID    # for runc (setns)
    mounts: # for runc
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /var/run/dhcp-client:/data
     - /usr/bin/runc:/usr/bin/runc # for runc
     - /run/runc:/run/runc         # for runc
     - /sbin:/sbin   # for ifconfig
     - /bin:/bin     # for ifconfig
     - /lib:/lib     # for ifconfig
services:
  - name: sshd
    image: linuxkit/sshd:75f399fbfb6455dfccd4cb30543d0b4b494d28c8
  - name: getty
    image: linuxkit/getty:5d86a2ce2d890c14ab66b13638dcadf74f29218b
    env:
     - INSECURE=true
files:
  - path: var/run/dhcp-client/README
    contents: 'data for dhcp-client'
  - path: root/.ssh/authorized_keys
    contents: '#your SSH key here'
