kernel:
  image: linuxkit/kernel:5.10.104
  cmdline: "console=ttyS0 page_poison=1"
init:
  - linuxkit/init:5251073a3d3e52881bf2697f7dfabac6eedfd569
  - linuxkit/runc:49628804b3a39b0a0cfab046dd80b76a4fd87b5a
  - linuxkit/containerd:c35f10fb8127841b4eb82ddfcebd5d5a54bad0e7
onboot:
  - name: sysctl
    image: linuxkit/sysctl:7c0059d1ad7d86127d990474b6e5f17297c07bf5
  - name: dhcp-client
    image: miragesdk/dhcp-client:22aa9d527820534295a8cd59901c0c5197af6585
    net: host
    capabilities:
     - CAP_NET_ADMIN # to bring eth0 up
     - CAP_NET_RAW   # to read /dev/eth0
     - CAP_SYS_ADMIN # for runc (unshare)
     - CAP_SETGID    # for runc (setns)
    mounts: # for runc
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /var/run/dhcp-client:/data
     - /usr/bin/runc:/usr/bin/runc # for runc
     - /run/runc:/run/runc         # for runc
     - /sbin:/sbin   # for ifconfig
     - /bin:/bin     # for ifconfig
     - /lib:/lib     # for ifconfig
services:
  - name: sshd
    image: linuxkit/sshd:e9ceec5f24261dbe15847de8c1c91245251e5814
  - name: getty
    image: linuxkit/getty:d421b06d0a1ae118e2af025cb7a3637f808a755b
    env:
     - INSECURE=true
files:
  - path: var/run/dhcp-client/README
    contents: 'data for dhcp-client'
  - path: root/.ssh/authorized_keys
    contents: '#your SSH key here'
