kernel:
  image: linuxkit/kernel:5.10.104
  cmdline: "console=ttyS0 page_poison=1"
init:
  - linuxkit/init:aa44b2891ae0273bd194bcf261dc75425713c034
  - linuxkit/runc:d02dbf3e72632831246ca9e2bc45772e2c3c02b8
  - linuxkit/containerd:4703525398adfe47764efbee8b36af79b4a6b097
onboot:
  - name: sysctl
    image: linuxkit/sysctl:0aa4b1141fb890d260bb1f8f43c399f2c5419b04
  - name: dhcp-client
    image: miragesdk/dhcp-client:22aa9d527820534295a8cd59901c0c5197af6585
    net: host
    capabilities:
     - CAP_NET_ADMIN # to bring eth0 up
     - CAP_NET_RAW   # to read /dev/eth0
     - CAP_SYS_ADMIN # for runc (unshare)
     - CAP_SETGID    # for runc (setns)
    mounts: # for runc
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /var/run/dhcp-client:/data
     - /usr/bin/runc:/usr/bin/runc # for runc
     - /run/runc:/run/runc         # for runc
     - /sbin:/sbin   # for ifconfig
     - /bin:/bin     # for ifconfig
     - /lib:/lib     # for ifconfig
services:
  - name: sshd
    image: linuxkit/sshd:62036c2a279715d05e8298b9269a0659964f2619
  - name: getty
    image: linuxkit/getty:4fbbfb7d2e78c8da9be51fc93b78b96685fb1809
    env:
     - INSECURE=true
files:
  - path: var/run/dhcp-client/README
    contents: 'data for dhcp-client'
  - path: root/.ssh/authorized_keys
    contents: '#your SSH key here'
