kernel:
  image: "linuxkitprojects/kernel-memorizer:4.10_dbg"
  cmdline: "console=ttyS0 page_poison=1"
init:
  - linuxkit/init:07d37c3ae7fad5ddcb54c8dc65774ae050851f04
  - linuxkit/runc:2aabf16bc8a1b94e015ee53fa2e7a77ab1883a80
  - linuxkit/containerd:95d5f0d2d8dc63bd87e96b7b39cf026cb86125c9
onboot:
  - name: dhcpcd
    image: linuxkit/dhcpcd:2a8ed08fea442909ba10f950d458191ed3647115
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: getty
    image: linuxkit/getty:e74e6cad132403d1a6d6cd25b136a7c69c99f3f7
    env:
     - INSECURE=true
trust:
  org:
    - linuxkit
