kernel:
  image: linuxkit/kernel-ima:4.11.1-186dd3605ee7b23214850142f8f02b4679dbd148
  cmdline: "console=ttyS0 console=tty0 page_poison=1 ima_appraise=enforce_ns"
init:
  - linuxkit/init:31dcd928602e39ee752843ebcf6c35cbae73c883
  - linuxkit/runc:7ecf2e5253905855fb554b072d42903f7829c8b6
  - linuxkit/containerd:f645aa2f8aa58023149d7766725039572a2ebeb5
  - linuxkit/ca-certificates:4ed09a382de2b3ba2143f4270375b3bd6e973fb5
  - linuxkit/ima-utils:dfeb3896fd29308b80ff9ba7fe5b8b767e40ca29
onboot:
  - name: sysctl
    image: linuxkit/sysctl:2f575c3d127824eb8d059673c538c440d22f19f5
  - name: dhcpcd
    image: linuxkit/dhcpcd:0cca76e71466fc6128fad585549b70538855f254
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: rngd
    image: linuxkit/rngd:fffdd86f314fd960235adf3fba0587d2266d7a0f
  - name: nginx
    image: nginx:1.13.8-alpine
    capabilities:
     - CAP_NET_BIND_SERVICE
     - CAP_CHOWN
     - CAP_SETUID
     - CAP_SETGID
     - CAP_DAC_OVERRIDE
files:
  - path: etc/docker/daemon.json
    contents: '{"debug": true}'
trust:
  org:
    - linuxkit
    - library
