kernel:
  image: linuxkit/kernel-ima:4.11.1-186dd3605ee7b23214850142f8f02b4679dbd148
  cmdline: "console=ttyS0 console=tty0 page_poison=1 ima_appraise=enforce_ns"
init:
  - linuxkit/init:5251073a3d3e52881bf2697f7dfabac6eedfd569
  - linuxkit/runc:49628804b3a39b0a0cfab046dd80b76a4fd87b5a
  - linuxkit/containerd:c35f10fb8127841b4eb82ddfcebd5d5a54bad0e7
  - linuxkit/ca-certificates:945ac3f0c1a31535d37ff77003fc30dbd71da6bb
  - linuxkit/ima-utils:dfeb3896fd29308b80ff9ba7fe5b8b767e40ca29
onboot:
  - name: sysctl
    image: linuxkit/sysctl:7c0059d1ad7d86127d990474b6e5f17297c07bf5
  - name: dhcpcd
    image: linuxkit/dhcpcd:fc2b5bf40b13df746ee66f354672bf687a540ce8
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: rngd
    image: linuxkit/rngd:97136824ad06ba2cc17c086d30f60c7f93b56f72
  - name: nginx
    image: nginx:1.13.8-alpine
    capabilities:
     - CAP_NET_BIND_SERVICE
     - CAP_CHOWN
     - CAP_SETUID
     - CAP_SETGID
     - CAP_DAC_OVERRIDE
files:
  - path: etc/docker/daemon.json
    contents: '{"debug": true}'
trust:
  org:
    - linuxkit
    - library
