kernel:
  image: linuxkit/kernel-ima:4.11.1-186dd3605ee7b23214850142f8f02b4679dbd148
  cmdline: "console=ttyS0 console=tty0 page_poison=1 ima_appraise=enforce_ns"
init:
  - linuxkit/init:ad37cb61355b08cf481c54b07612b5206be6254d
  - linuxkit/runc:8c00a7c58393f0cfcab81ac4171c00bcaec6b962
  - linuxkit/containerd:26f04b0b57e3d21bfb36732b5c6ebe8f08c6705b
  - linuxkit/ca-certificates:a37095d3d576815fdefe76a28444c68cd9eac8fe
  - linuxkit/ima-utils:dfeb3896fd29308b80ff9ba7fe5b8b767e40ca29
onboot:
  - name: sysctl
    image: linuxkit/sysctl:984bff0476b059ae86b4c3e7c15f93f72a5d0a57
  - name: dhcpcd
    image: linuxkit/dhcpcd:0060977dc2cd15eb242c21888fad240f96ec7308
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: rngd
    image: linuxkit/rngd:f46ebc10118bac79f68607c3c3308f0da8d9bde3
  - name: nginx
    image: nginx:1.13.8-alpine
    capabilities:
     - CAP_NET_BIND_SERVICE
     - CAP_CHOWN
     - CAP_SETUID
     - CAP_SETGID
     - CAP_DAC_OVERRIDE
files:
  - path: etc/docker/daemon.json
    contents: '{"debug": true}'
trust:
  org:
    - linuxkit
    - library
