kernel:
  image: linuxkit/kernel-ima:4.11.1-186dd3605ee7b23214850142f8f02b4679dbd148
  cmdline: "console=ttyS0 console=tty0 page_poison=1 ima_appraise=enforce_ns"
init:
  - linuxkit/init:7e8c0f9a968894f6f8be80bfb99b3e16d201e50b
  - linuxkit/runc:86b8092f0ad8635cc8b6b1c95a4b20f66c4095bb
  - linuxkit/containerd:1b14966d84209083c9cbc757be862f97005e5796
  - linuxkit/ca-certificates:b1afe194ecb800d2b947e24c9e780c959fd3668f
  - linuxkit/ima-utils:dfeb3896fd29308b80ff9ba7fe5b8b767e40ca29
onboot:
  - name: sysctl
    image: linuxkit/sysctl:cf714d65c0df9ff0f0cccf4a3d4ff4157ddef903
  - name: dhcpcd
    image: linuxkit/dhcpcd:cf2f1bb633284e0c2b0745c9d29aee66fab449aa
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: rngd
    image: linuxkit/rngd:4bbcd2fc645f2387c98980aa9f8b19c62805d06f
  - name: nginx
    image: nginx:1.13.8-alpine
    capabilities:
     - CAP_NET_BIND_SERVICE
     - CAP_CHOWN
     - CAP_SETUID
     - CAP_SETGID
     - CAP_DAC_OVERRIDE
files:
  - path: etc/docker/daemon.json
    contents: '{"debug": true}'
trust:
  org:
    - linuxkit
    - library
