kernel:
  image: linuxkit/kernel:5.10.104
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:7e8c0f9a968894f6f8be80bfb99b3e16d201e50b
  - linuxkit/runc:86b8092f0ad8635cc8b6b1c95a4b20f66c4095bb
  - linuxkit/containerd:1b14966d84209083c9cbc757be862f97005e5796
  - linuxkit/ca-certificates:b1afe194ecb800d2b947e24c9e780c959fd3668f
onboot:
  - name: sysctl
    image: linuxkit/sysctl:cf714d65c0df9ff0f0cccf4a3d4ff4157ddef903
  - name: dhcpcd
    image: linuxkit/dhcpcd:cf2f1bb633284e0c2b0745c9d29aee66fab449aa
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: sysfs
    image: linuxkit/sysfs:72b2041ed8b9ab95475a5ed0e5b208b1aca669eb
  - name: format
    image: linuxkit/format:68af8bc2e992f2f591afc9c628cfe35296616193
  - name: mount
    image: linuxkit/mount:ef198f6e9f4f9ee51a94daa90f3ebac67f7ee31e
    command: ["/usr/bin/mountie", "/var/lib/docker"]

services:
  - name: getty
    image: linuxkit/getty:e594a89dc1aee9b40cb0febcbdf207a5c2506c0e
    env:
      - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:4bbcd2fc645f2387c98980aa9f8b19c62805d06f
  - name: ntpd
    image: linuxkit/openntpd:3d4f9c34269471e9bee76a73dc5168d8a4c8d990

  - name: docker
    image: docker:20.10.6-dind
    capabilities:
      - all
    net: host
    mounts:
      - type: cgroup
        options: ["rw", "nosuid", "noexec", "nodev", "relatime"]
    binds:
      - /etc/resolv.conf:/etc/resolv.conf
      - /var/lib/docker:/var/lib/docker
      - /var/run:/var/run
      - /lib/modules:/lib/modules
      - /etc/docker/daemon.json:/etc/docker/daemon.json
    command: ["/usr/local/bin/docker-init", "/usr/local/bin/dockerd"]
  - name: cadvisor
    image: linuxkit/cadvisor:e2ef4b703a4df2e779184243033047fd932e9637
files:
  - path: var/lib/docker
    directory: true
  - path: etc/docker/daemon.json
    contents: '{"debug": true, "hosts": ["unix:///var/run/docker.sock"]}'
    mode: "0644"
