kernel:
  image: linuxkit/kernel:5.10.104
  cmdline: "console=tty0 console=ttyS0"
init:
  - linuxkit/init:07d37c3ae7fad5ddcb54c8dc65774ae050851f04
  - linuxkit/runc:2aabf16bc8a1b94e015ee53fa2e7a77ab1883a80
  - linuxkit/containerd:95d5f0d2d8dc63bd87e96b7b39cf026cb86125c9
  - linuxkit/ca-certificates:4de36e93dc87f7ccebd20db616ed10d381911d32
onboot:
  - name: sysctl
    image: linuxkit/sysctl:c6f23919b8610c7645a89a89f863c6209bc84bee
  - name: dhcpcd
    image: linuxkit/dhcpcd:2a8ed08fea442909ba10f950d458191ed3647115
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: format
    image: linuxkit/format:5161fe240e5824da04d51bcf5e00afcb0c18dc25
    command: ["/usr/bin/format", "/dev/sda"]
  - name: mount
    image: linuxkit/mount:f671cb94a8999a65e33b3fe79f3def58e3d58b07
    command: ["/usr/bin/mountie", "/dev/sda1", "/var/external"]
  - name: loop
    image: linuxkit/losetup:fcee8e453684d45c3c411fe8c28ecb2210158638
    command: ["/usr/bin/loopy", "--create", "/var/external/storage_file"]
  - name: dm-crypt
    image: linuxkit/dm-crypt:526d32351c8246431be8e1a168cb514ff3c365af
    command: ["/usr/bin/crypto", "crypt_loop_dev", "/dev/loop0"]
  - name: mount
    image: linuxkit/mount:f671cb94a8999a65e33b3fe79f3def58e3d58b07
    command: ["/usr/bin/mountie", "/dev/mapper/crypt_loop_dev", "/var/secure_storage"]
  - name: bbox
    image: busybox
    command: ["sh", "-c", "echo 'secret things' >/var/secure_storage/secrets"]
    binds:
      - /var:/var
services:
  - name: getty
    image: linuxkit/getty:e74e6cad132403d1a6d6cd25b136a7c69c99f3f7
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:310c16ec5315bd07d4b8f5332cfa7dc5cbc7d368
files:
  - path: etc/dm-crypt/key
    # the below key is just to keep the example self-contained
    # !!! provide a proper key for production use here !!!
    contents: "abcdefghijklmnopqrstuvwxyz123456"
