kernel:
  image: linuxkit/kernel:5.10.104
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:ad37cb61355b08cf481c54b07612b5206be6254d
  - linuxkit/runc:8c00a7c58393f0cfcab81ac4171c00bcaec6b962
  - linuxkit/containerd:26f04b0b57e3d21bfb36732b5c6ebe8f08c6705b
  - linuxkit/ca-certificates:a37095d3d576815fdefe76a28444c68cd9eac8fe
onboot:
  - name: sysctl
    image: linuxkit/sysctl:984bff0476b059ae86b4c3e7c15f93f72a5d0a57
  - name: sysfs
    image: linuxkit/sysfs:e7910655e4b320b769bb7e5819f33e0d097c98c4
  - name: format
    image: linuxkit/format:97dcd726d14ce2ef767d674adb8a709d5a73c213
  - name: mount
    image: linuxkit/mount:ce11bd5f816af89ba0760853420aa988b98cda13
    command: ["/usr/bin/mountie", "/var/lib/docker"]
services:
  - name: getty
    image: linuxkit/getty:97d0743bc3baa349dc96809b58f8584c5896928a
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:f46ebc10118bac79f68607c3c3308f0da8d9bde3
  - name: dhcpcd
    image: linuxkit/dhcpcd:0060977dc2cd15eb242c21888fad240f96ec7308
  - name: ntpd
    image: linuxkit/openntpd:2a6439b4f52cd694d139f5445287d9f09e392a92
  - name: docker
    image: docker:20.10.6-dind
    capabilities:
     - all
    net: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
     - /var/lib/docker:/var/lib/docker
     - /lib/modules:/lib/modules
     - /etc/docker/daemon.json:/etc/docker/daemon.json
    command: ["/usr/local/bin/docker-init", "/usr/local/bin/dockerd"]
files:
  - path: var/lib/docker
    directory: true
  - path: etc/docker/daemon.json
    contents: '{"debug": true}'
