kernel:
  image: linuxkit/kernel:5.10.104
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:aa44b2891ae0273bd194bcf261dc75425713c034
  - linuxkit/runc:d02dbf3e72632831246ca9e2bc45772e2c3c02b8
  - linuxkit/containerd:4703525398adfe47764efbee8b36af79b4a6b097
  - linuxkit/ca-certificates:4de36e93dc87f7ccebd20db616ed10d381911d32
onboot:
  - name: sysctl
    image: linuxkit/sysctl:0aa4b1141fb890d260bb1f8f43c399f2c5419b04
  - name: sysfs
    image: linuxkit/sysfs:5fd982d39ff7bec8e480c67a110acb2d3794c291
  - name: format
    image: linuxkit/format:5161fe240e5824da04d51bcf5e00afcb0c18dc25
  - name: mount
    image: linuxkit/mount:f671cb94a8999a65e33b3fe79f3def58e3d58b07
    command: ["/usr/bin/mountie", "/var/lib/docker"]
services:
  - name: getty
    image: linuxkit/getty:4fbbfb7d2e78c8da9be51fc93b78b96685fb1809
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:310c16ec5315bd07d4b8f5332cfa7dc5cbc7d368
  - name: dhcpcd
    image: linuxkit/dhcpcd:2a8ed08fea442909ba10f950d458191ed3647115
  - name: ntpd
    image: linuxkit/openntpd:dd353cac6cbd816008c565041cec6650090d0ad0
  - name: docker
    image: docker:20.10.6-dind
    capabilities:
     - all
    net: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
     - /var/lib/docker:/var/lib/docker
     - /lib/modules:/lib/modules
     - /etc/docker/daemon.json:/etc/docker/daemon.json
    command: ["/usr/local/bin/docker-init", "/usr/local/bin/dockerd"]
files:
  - path: var/lib/docker
    directory: true
  - path: etc/docker/daemon.json
    contents: '{"debug": true}'
