kernel:
  image: linuxkit/kernel:6.6.13
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:872d2e1be745f1acb948762562cf31c367303a3b
  - linuxkit/runc:6062483d748609d505f2bcde4e52ee64a3329f5f
  - linuxkit/containerd:39301e7312f13eedf19bd5d5551af7b37001d435
  - linuxkit/ca-certificates:5aaa343474e5ac3ac01f8b917e82efb1063d80ff
onboot:
  - name: sysctl
    image: linuxkit/sysctl:5a374e4bf3e5a7deeacff6571d0f30f7ea8f56db
  - name: dhcpcd
    image: linuxkit/dhcpcd:e9e3580f2de00e73e7b316a007186d22fea056ee
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: getty
    image: linuxkit/getty:5d86a2ce2d890c14ab66b13638dcadf74f29218b
    # to make insecure with passwordless root login, uncomment following lines
    #env:
    # - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:83a6481f04da73e710c1d416355920b8ff4dc1dd
files:
  - path: etc/getty.shadow
    # sample sets password for root to "abcdefgh" (without quotes)
    contents: 'root:$6$6tPd2uhHrecCEKug$8mKfcgfwguP7f.BLdZsT1Wz7WIIJOBY1oUFHzIv9/O71M2J0EPdtFqFGTxB1UK5ejqQxRFQ.ZSG9YXR0SNsc11:17322:0:::::'
