kernel:
  image: linuxkit/kernel:6.6.13
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:e120ea2a30d906bd1ee1874973d6e4b1403b5ca3
  - linuxkit/runc:6062483d748609d505f2bcde4e52ee64a3329f5f
  - linuxkit/containerd:39301e7312f13eedf19bd5d5551af7b37001d435
  - linuxkit/ca-certificates:5aaa343474e5ac3ac01f8b917e82efb1063d80ff
onboot:
  - name: dhcpcd
    image: linuxkit/dhcpcd:e9e3580f2de00e73e7b316a007186d22fea056ee
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: getty
    image: linuxkit/getty:5d86a2ce2d890c14ab66b13638dcadf74f29218b
    env:
     - INSECURE=true
  - name: influxdb
    image: influxdb:1.7
    net: host
    capabilities:
      - CAP_NET_BIND_SERVICE
      - CAP_DAC_OVERRIDE
  - name: kapacitor
    image: kapacitor:1.5
    net: host
    capabilities:
      - all
    env:
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
  - name: telegraf
    image: telegraf:1.9
    net: host
    capabilities:
      - all
  - name: chronograf
    image: chronograf:1.7
    net: host
    capabilities:
      - CAP_NET_BIND_SERVICE
      - CAP_DAC_OVERRIDE
    env:
      - INFLUXDB_URL=http://127.0.0.1:8086
      - KAPACITOR_URL=http://127.0.0.1:9092
