kernel:
  image: linuxkit/kernel:5.10.104
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:7e8c0f9a968894f6f8be80bfb99b3e16d201e50b
  - linuxkit/runc:86b8092f0ad8635cc8b6b1c95a4b20f66c4095bb
  - linuxkit/containerd:1b14966d84209083c9cbc757be862f97005e5796
  - linuxkit/ca-certificates:b1afe194ecb800d2b947e24c9e780c959fd3668f
onboot:
  - name: dhcpcd
    image: linuxkit/dhcpcd:cf2f1bb633284e0c2b0745c9d29aee66fab449aa
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: getty
    image: linuxkit/getty:e594a89dc1aee9b40cb0febcbdf207a5c2506c0e
    env:
     - INSECURE=true
  - name: influxdb
    image: influxdb:1.7
    net: host
    capabilities:
      - CAP_NET_BIND_SERVICE
      - CAP_DAC_OVERRIDE
  - name: kapacitor
    image: kapacitor:1.5
    net: host
    capabilities:
      - all
    env:
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
  - name: telegraf
    image: telegraf:1.9
    net: host
    capabilities:
      - all
  - name: chronograf
    image: chronograf:1.7
    net: host
    capabilities:
      - CAP_NET_BIND_SERVICE
      - CAP_DAC_OVERRIDE
    env:
      - INFLUXDB_URL=http://127.0.0.1:8086
      - KAPACITOR_URL=http://127.0.0.1:9092
