kernel:
  image: linuxkit/kernel:5.10.104
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:31dcd928602e39ee752843ebcf6c35cbae73c883
  - linuxkit/runc:7ecf2e5253905855fb554b072d42903f7829c8b6
  - linuxkit/containerd:f645aa2f8aa58023149d7766725039572a2ebeb5
  - linuxkit/ca-certificates:4ed09a382de2b3ba2143f4270375b3bd6e973fb5
onboot:
  - name: dhcpcd
    image: linuxkit/dhcpcd:0cca76e71466fc6128fad585549b70538855f254
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: getty
    image: linuxkit/getty:ccac1189f78ff466b76d097a0b7b7236ea54de84
    env:
     - INSECURE=true
  - name: influxdb
    image: influxdb:1.7
    net: host
    capabilities:
      - CAP_NET_BIND_SERVICE
      - CAP_DAC_OVERRIDE
  - name: kapacitor
    image: kapacitor:1.5
    net: host
    capabilities:
      - all
    env:
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
  - name: telegraf
    image: telegraf:1.9
    net: host
    capabilities:
      - all
  - name: chronograf
    image: chronograf:1.7
    net: host
    capabilities:
      - CAP_NET_BIND_SERVICE
      - CAP_DAC_OVERRIDE
    env:
      - INFLUXDB_URL=http://127.0.0.1:8086
      - KAPACITOR_URL=http://127.0.0.1:9092
