# Simple example of using an external logging service
kernel:
  image: linuxkit/kernel:5.10.104
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:aa44b2891ae0273bd194bcf261dc75425713c034
  - linuxkit/runc:d02dbf3e72632831246ca9e2bc45772e2c3c02b8
  - linuxkit/containerd:4703525398adfe47764efbee8b36af79b4a6b097
  - linuxkit/ca-certificates:4de36e93dc87f7ccebd20db616ed10d381911d32
  - linuxkit/memlogd:9fe3a579b45200edeb3dce7ce3e95a40878c374b
onboot:
  - name: sysctl
    image: linuxkit/sysctl:0aa4b1141fb890d260bb1f8f43c399f2c5419b04
  - name: dhcpcd
    image: linuxkit/dhcpcd:2a8ed08fea442909ba10f950d458191ed3647115
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
# Inside the getty type `/proc/1/root/usr/bin/logread -F` to follow the log
  - name: getty
    image: linuxkit/getty:4fbbfb7d2e78c8da9be51fc93b78b96685fb1809
    env:
     - INSECURE=true
# A service which generates log messages for testing
  - name: write-to-the-logs
    image: alpine:3.13
    command: ["/bin/sh", "-c", "while /bin/true; do echo hello $(date); sleep 1; done" ]
  - name: write-and-rotate-logs
    image: linuxkit/logwrite:107c407b3443fb04eb0a6f69182653836c4e62f9
  - name: kmsg
    image: linuxkit/kmsg:ba81a0a3029b4bb7ee455f73892da9667397ca5b
