kernel:
  image: linuxkit/kernel:5.10.104
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0 root=/dev/vda"
init:
  - linuxkit/init:817099ace2d56ea2d20c7702ab8e1a8abc7d89fd
  - linuxkit/runc:59c40661f2174ca6752d73086b91d63eeb98d021
  - linuxkit/containerd:0dab9a4e2b9aa7f034873881a08890fd40b2755d
  - linuxkit/ca-certificates:6003d7e78387f1fbb35bf1d1af300120be97f94b
onboot:
  - name: sysctl
    image: linuxkit/sysctl:f8a06fea01bfcb322e913213e22d35790168ed01
  - name: rngd1
    image: linuxkit/rngd:e35c1c671a9d35dbc42b83b620563ce472f8effb
    command: ["/sbin/rngd", "-1"]
  - name: dhcpcd
    image: linuxkit/dhcpcd:a58543e8b40a29b3cd0c5d1e42ce21b71a8abcef
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: metadata
    image: linuxkit/metadata:420ead0d86604a6dc138c393914d419b68e50e04
services:
  - name: getty
    image: linuxkit/getty:9b8e6b510b49da196a1e412aa95f364e3dd16576
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:e35c1c671a9d35dbc42b83b620563ce472f8effb
