kernel:
  image: linuxkit/kernel:5.10.104
  cmdline: console=ttyS1
  ucode: intel-ucode.cpio
init:
  - linuxkit/init:31dcd928602e39ee752843ebcf6c35cbae73c883
  - linuxkit/runc:7ecf2e5253905855fb554b072d42903f7829c8b6
  - linuxkit/containerd:f645aa2f8aa58023149d7766725039572a2ebeb5
  - linuxkit/ca-certificates:4ed09a382de2b3ba2143f4270375b3bd6e973fb5
  - linuxkit/firmware:332dc11c1ba110dfe6acaeb7c95a3f597d7f1f21
onboot:
  - name: rngd1
    image: linuxkit/rngd:fffdd86f314fd960235adf3fba0587d2266d7a0f
    command: ["/sbin/rngd", "-1"]
  - name: sysctl
    image: linuxkit/sysctl:2f575c3d127824eb8d059673c538c440d22f19f5
  - name: dhcpcd
    image: linuxkit/dhcpcd:0cca76e71466fc6128fad585549b70538855f254
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: metadata
    image: linuxkit/metadata:a5df09643d7ac6565295cad633c3d63489c3d4df
    command: ["/usr/bin/metadata", "hetzner"]
services:
  - name: rngd
    image: linuxkit/rngd:fffdd86f314fd960235adf3fba0587d2266d7a0f
  - name: getty
    image: linuxkit/getty:ccac1189f78ff466b76d097a0b7b7236ea54de84
    env:
     - INSECURE=true
  - name: sshd
    image: linuxkit/sshd:d7286e080dc56a2d5718d20e51efbe32123f83ba
    binds.add:
      - /root/.ssh:/root/.ssh
files:
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true
