kernel:
  image: linuxkit/kernel:5.11.4-rt
  cmdline: "console=tty0"
init:
  - linuxkit/init:7e8c0f9a968894f6f8be80bfb99b3e16d201e50b
  - linuxkit/runc:86b8092f0ad8635cc8b6b1c95a4b20f66c4095bb
  - linuxkit/containerd:1b14966d84209083c9cbc757be862f97005e5796
  - linuxkit/ca-certificates:b1afe194ecb800d2b947e24c9e780c959fd3668f
onboot:
  - name: sysctl
    image: linuxkit/sysctl:cf714d65c0df9ff0f0cccf4a3d4ff4157ddef903
services:
  - name: getty
    image: linuxkit/getty:e594a89dc1aee9b40cb0febcbdf207a5c2506c0e
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:4bbcd2fc645f2387c98980aa9f8b19c62805d06f
  - name: dhcpcd
    image: linuxkit/dhcpcd:cf2f1bb633284e0c2b0745c9d29aee66fab449aa
  - name: open-vm-tools
    image: linuxkit/open-vm-tools:4c621e60c0ead067204a2e48280ffd7b3a46633b
  - name: nginx
    image: nginx:1.13.8-alpine
    capabilities:
     - CAP_NET_BIND_SERVICE
     - CAP_CHOWN
     - CAP_SETUID
     - CAP_SETGID
     - CAP_DAC_OVERRIDE
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
