kernel:
  image: linuxkit/kernel:5.10.104
  cmdline: "console=ttyS0"
init:
  - linuxkit/init:7e8c0f9a968894f6f8be80bfb99b3e16d201e50b
  - linuxkit/runc:86b8092f0ad8635cc8b6b1c95a4b20f66c4095bb
  - linuxkit/containerd:1b14966d84209083c9cbc757be862f97005e5796
  - linuxkit/ca-certificates:b1afe194ecb800d2b947e24c9e780c959fd3668f
onboot:
  - name: sysctl
    image: linuxkit/sysctl:cf714d65c0df9ff0f0cccf4a3d4ff4157ddef903
services:
  - name: rngd
    image: linuxkit/rngd:4bbcd2fc645f2387c98980aa9f8b19c62805d06f
  - name: dhcpcd
    image: linuxkit/dhcpcd:cf2f1bb633284e0c2b0745c9d29aee66fab449aa
  - name: sshd
    image: linuxkit/sshd:a444e6e4a82a1515cbc40e4321dfb29f5e6f8c24
    binds.add:
      - /root/.ssh:/root/.ssh
files:
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true
