kernel:
  image: linuxkit/kernel:6.6.13
  cmdline: console=ttyS1
  ucode: intel-ucode.cpio
init:
  - linuxkit/init:e6f99bdda1628d47f59dab20c85794b4ea6fad95
  - linuxkit/runc:6062483d748609d505f2bcde4e52ee64a3329f5f
  - linuxkit/containerd:39301e7312f13eedf19bd5d5551af7b37001d435
  - linuxkit/ca-certificates:5aaa343474e5ac3ac01f8b917e82efb1063d80ff
  - linuxkit/firmware:8def159583422181ddee3704f7024ecb9c02d348
onboot:
  - name: rngd1
    image: linuxkit/rngd:83a6481f04da73e710c1d416355920b8ff4dc1dd
    command: ["/sbin/rngd", "-1"]
  - name: sysctl
    image: linuxkit/sysctl:5a374e4bf3e5a7deeacff6571d0f30f7ea8f56db
  - name: dhcpcd
    image: linuxkit/dhcpcd:e9e3580f2de00e73e7b316a007186d22fea056ee
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: metadata
    image: linuxkit/metadata:b082f1bf97a9034d1e4c0e36a5d2923f4e58f540
    command: ["/usr/bin/metadata", "hetzner"]
services:
  - name: rngd
    image: linuxkit/rngd:83a6481f04da73e710c1d416355920b8ff4dc1dd
  - name: getty
    image: linuxkit/getty:5d86a2ce2d890c14ab66b13638dcadf74f29218b
    env:
     - INSECURE=true
  - name: sshd
    image: linuxkit/sshd:75f399fbfb6455dfccd4cb30543d0b4b494d28c8
    binds.add:
      - /root/.ssh:/root/.ssh
files:
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true
