kernel:
  image: linuxkit/kernel:5.10.104
  cmdline: "console=ttyS0"
init:
  - linuxkit/init:07d37c3ae7fad5ddcb54c8dc65774ae050851f04
  - linuxkit/runc:2aabf16bc8a1b94e015ee53fa2e7a77ab1883a80
  - linuxkit/containerd:95d5f0d2d8dc63bd87e96b7b39cf026cb86125c9
  - linuxkit/ca-certificates:4de36e93dc87f7ccebd20db616ed10d381911d32
onboot:
  - name: sysctl
    image: linuxkit/sysctl:c6f23919b8610c7645a89a89f863c6209bc84bee
  - name: dhcpcd
    image: linuxkit/dhcpcd:2a8ed08fea442909ba10f950d458191ed3647115
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: metadata
    image: linuxkit/metadata:501144d47215671e77b9cac44748a04f21236195
    command: ["/usr/bin/metadata", "vultr"]
services:
  - name: getty
    image: linuxkit/getty:e74e6cad132403d1a6d6cd25b136a7c69c99f3f7
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:310c16ec5315bd07d4b8f5332cfa7dc5cbc7d368
  - name: sshd
    image: linuxkit/sshd:62036c2a279715d05e8298b9269a0659964f2619
    binds.add:
     - /run/config/ssh/authorized_keys:/root/.ssh/authorized_keys
  - name: nginx
    image: nginx:1.13.8-alpine
    capabilities:
     - CAP_NET_BIND_SERVICE
     - CAP_CHOWN
     - CAP_SETUID
     - CAP_SETGID
     - CAP_DAC_OVERRIDE
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
