kernel:
  image: linuxkit/kernel:5.10.104
  cmdline: console=ttyS1
  ucode: intel-ucode.cpio
init:
  - linuxkit/init:ad37cb61355b08cf481c54b07612b5206be6254d
  - linuxkit/runc:8c00a7c58393f0cfcab81ac4171c00bcaec6b962
  - linuxkit/containerd:26f04b0b57e3d21bfb36732b5c6ebe8f08c6705b
  - linuxkit/ca-certificates:a37095d3d576815fdefe76a28444c68cd9eac8fe
  - linuxkit/firmware:daefe8d1cbe45f2365338a9f731584691b9e79d9
onboot:
  - name: rngd1
    image: linuxkit/rngd:f46ebc10118bac79f68607c3c3308f0da8d9bde3
    command: ["/sbin/rngd", "-1"]
  - name: sysctl
    image: linuxkit/sysctl:984bff0476b059ae86b4c3e7c15f93f72a5d0a57
  - name: dhcpcd
    image: linuxkit/dhcpcd:0060977dc2cd15eb242c21888fad240f96ec7308
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: metadata
    image: linuxkit/metadata:fa7dda444e6cfcdaad696a013364d53c9ebebd62
    command: ["/usr/bin/metadata", "packet"]
services:
  - name: rngd
    image: linuxkit/rngd:f46ebc10118bac79f68607c3c3308f0da8d9bde3
  - name: getty
    image: linuxkit/getty:97d0743bc3baa349dc96809b58f8584c5896928a
    env:
     - INSECURE=true
  - name: sshd
    image: linuxkit/sshd:c8490aea913425c779c41bb2990e09839190452d
    binds.add:
      - /root/.ssh:/root/.ssh
files:
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true
