# Minimal YAML to run a redis server (used at DockerCon'17)
# connect: nc localhost 6379
kernel:
  image: linuxkit/kernel:5.10.104
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:ad37cb61355b08cf481c54b07612b5206be6254d
  - linuxkit/runc:8c00a7c58393f0cfcab81ac4171c00bcaec6b962
  - linuxkit/containerd:26f04b0b57e3d21bfb36732b5c6ebe8f08c6705b
onboot:
  - name: dhcpcd
    image: linuxkit/dhcpcd:0060977dc2cd15eb242c21888fad240f96ec7308
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: getty
    image: linuxkit/getty:97d0743bc3baa349dc96809b58f8584c5896928a
    env:
     - INSECURE=true
  # Currently redis:4.0.6-alpine has trust issue with multi-arch
  # https://github.com/docker-library/official-images/issues/3794
  - name: redis
    image: redis:4.0.5-alpine
    capabilities:
     - CAP_NET_BIND_SERVICE
     - CAP_CHOWN
     - CAP_SETUID
     - CAP_SETGID
     - CAP_DAC_OVERRIDE
    net: host
