kernel:
  image: linuxkit/kernel:6.6.13
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:59b5282b07b782091de8915ac30b512a227f72f9
  - linuxkit/runc:6062483d748609d505f2bcde4e52ee64a3329f5f
  - linuxkit/containerd:39301e7312f13eedf19bd5d5551af7b37001d435
  - linuxkit/ca-certificates:5aaa343474e5ac3ac01f8b917e82efb1063d80ff
onboot:
  - name: sysctl
    image: linuxkit/sysctl:5a374e4bf3e5a7deeacff6571d0f30f7ea8f56db
  - name: rngd1
    image: linuxkit/rngd:83a6481f04da73e710c1d416355920b8ff4dc1dd
    command: ["/sbin/rngd", "-1"]
services:
  - name: getty
    image: linuxkit/getty:5d86a2ce2d890c14ab66b13638dcadf74f29218b
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:83a6481f04da73e710c1d416355920b8ff4dc1dd
  - name: dhcpcd
    image: linuxkit/dhcpcd:e9e3580f2de00e73e7b316a007186d22fea056ee
  - name: sshd
    image: linuxkit/sshd:75f399fbfb6455dfccd4cb30543d0b4b494d28c8
    binds.add:
      - /root/.ssh:/root/.ssh
files:
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true
