kernel:
  image: linuxkit/kernel:5.10.104
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:07d37c3ae7fad5ddcb54c8dc65774ae050851f04
  - linuxkit/runc:2aabf16bc8a1b94e015ee53fa2e7a77ab1883a80
  - linuxkit/containerd:95d5f0d2d8dc63bd87e96b7b39cf026cb86125c9
  - linuxkit/ca-certificates:4de36e93dc87f7ccebd20db616ed10d381911d32
onboot:
  - name: sysctl
    image: linuxkit/sysctl:c6f23919b8610c7645a89a89f863c6209bc84bee
  - name: dhcpcd
    image: linuxkit/dhcpcd:2a8ed08fea442909ba10f950d458191ed3647115
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: format
    image: linuxkit/format:5161fe240e5824da04d51bcf5e00afcb0c18dc25
  - name: mount
    image: linuxkit/mount:f671cb94a8999a65e33b3fe79f3def58e3d58b07
    command: ["/usr/bin/mountie", "/var/external"]
  - name: swap
    image: linuxkit/swap:d17a7f1c26ff768c26b3c206ccf3aa72349568df
    # to use unencrypted swap, use:
    # command: ["/swap.sh", "--path", "/var/external/swap", "--size", "1G"]
    command: ["/swap.sh", "--path", "/var/external/swap", "--size", "1G", "--encrypt"]
services:
  - name: getty
    image: linuxkit/getty:e74e6cad132403d1a6d6cd25b136a7c69c99f3f7
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:310c16ec5315bd07d4b8f5332cfa7dc5cbc7d368
