kernel:
  image: linuxkit/kernel:5.10.104
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:817099ace2d56ea2d20c7702ab8e1a8abc7d89fd
  - linuxkit/runc:59c40661f2174ca6752d73086b91d63eeb98d021
  - linuxkit/containerd:0dab9a4e2b9aa7f034873881a08890fd40b2755d
  - linuxkit/ca-certificates:6003d7e78387f1fbb35bf1d1af300120be97f94b
onboot:
  - name: sysctl
    image: linuxkit/sysctl:f8a06fea01bfcb322e913213e22d35790168ed01
  - name: dhcpcd
    image: linuxkit/dhcpcd:a58543e8b40a29b3cd0c5d1e42ce21b71a8abcef
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: format
    image: linuxkit/format:4686064ce75f8014a3cdf8c3227887a81a74180a
  - name: mount
    image: linuxkit/mount:e3f4f07c424c1aff42a3b2009fb701540e313056
    command: ["/usr/bin/mountie", "/var/external"]
  - name: swap
    image: linuxkit/swap:ace4fd36355cd24cb8428122f46a2ae8a113d9ac
    # to use unencrypted swap, use:
    # command: ["/swap.sh", "--path", "/var/external/swap", "--size", "1G"]
    command: ["/swap.sh", "--path", "/var/external/swap", "--size", "1G", "--encrypt"]
services:
  - name: getty
    image: linuxkit/getty:9b8e6b510b49da196a1e412aa95f364e3dd16576
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:e35c1c671a9d35dbc42b83b620563ce472f8effb
