kernel:
  image: linuxkit/kernel:5.10.104
  cmdline: "console=ttyS0"
init:
  - linuxkit/init:817099ace2d56ea2d20c7702ab8e1a8abc7d89fd
  - linuxkit/runc:59c40661f2174ca6752d73086b91d63eeb98d021
  - linuxkit/containerd:0dab9a4e2b9aa7f034873881a08890fd40b2755d
onboot:
  - name: dhcpcd
    image: linuxkit/dhcpcd:a58543e8b40a29b3cd0c5d1e42ce21b71a8abcef
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: mount-vpnkit
    image: alpine:3.13
    binds:
        - /var/:/host_var:rbind,rshared
    capabilities:
        - CAP_SYS_ADMIN
    rootfsPropagation: shared
    command: ["sh", "-c", "mkdir /host_var/vpnkit && mount -v -t 9p -o trans=virtio,dfltuid=1001,dfltgid=50,version=9p2000 port /host_var/vpnkit"]
services:
  - name: sshd
    image: linuxkit/sshd:3d3847cf029b1b600b97011f78aa015315b2cb78
    binds.add:
      - /root/.ssh:/root/.ssh
  - name: vpnkit-forwarder
    image: linuxkit/vpnkit-forwarder:9a2cb62b40426b271db8ba35dca538db05bc9220
    binds:
        - /var/vpnkit:/port
    net: host
    command: ["/vpnkit-forwarder"]

files:
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true
