kernel:
  image: linuxkit/kernel:5.10.104
  cmdline: "console=ttyS0"
init:
  - linuxkit/init:aa44b2891ae0273bd194bcf261dc75425713c034
  - linuxkit/runc:d02dbf3e72632831246ca9e2bc45772e2c3c02b8
  - linuxkit/containerd:4703525398adfe47764efbee8b36af79b4a6b097
onboot:
  - name: dhcpcd
    image: linuxkit/dhcpcd:2a8ed08fea442909ba10f950d458191ed3647115
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: vsudd
    image: linuxkit/vsudd:5b962bdd22524b4edb7f428de745376abe359596
    binds:
        - /run/containerd/containerd.sock:/run/containerd/containerd.sock
    command: ["/vsudd",
        "-inport", "2374:unix:/run/containerd/containerd.sock"]
