kernel:
  image: linuxkit/kernel:5.10.104
  cmdline: "console=ttyS0"
init:
  - linuxkit/init:ad37cb61355b08cf481c54b07612b5206be6254d
  - linuxkit/runc:8c00a7c58393f0cfcab81ac4171c00bcaec6b962
  - linuxkit/containerd:26f04b0b57e3d21bfb36732b5c6ebe8f08c6705b
onboot:
  - name: dhcpcd
    image: linuxkit/dhcpcd:0060977dc2cd15eb242c21888fad240f96ec7308
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: vsudd
    image: linuxkit/vsudd:95b76be440be0a0dd8de44f0532c897e7df9d1d9
    binds:
        - /run/containerd/containerd.sock:/run/containerd/containerd.sock
    command: ["/vsudd",
        "-inport", "2374:unix:/run/containerd/containerd.sock"]
