kernel:
  image: linuxkit/kernel:5.10.104
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:aa44b2891ae0273bd194bcf261dc75425713c034
  - linuxkit/runc:d02dbf3e72632831246ca9e2bc45772e2c3c02b8
  - linuxkit/containerd:4703525398adfe47764efbee8b36af79b4a6b097
  - linuxkit/ca-certificates:4de36e93dc87f7ccebd20db616ed10d381911d32
onboot:
  - name: sysctl
    image: linuxkit/sysctl:0aa4b1141fb890d260bb1f8f43c399f2c5419b04
  - name: dhcpcd
    image: linuxkit/dhcpcd:2a8ed08fea442909ba10f950d458191ed3647115
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: wg0
    image: linuxkit/ip:c88e3272e3b12edec454e4720da8bb70a7655bc7
    net: new
    binds:
      - /etc/wireguard:/etc/wireguard
    command: ["/usr/bin/lk-wg-config", "configure", "/etc/wireguard/wg0.conf"]
    runtime:
      interfaces:
        - name: wg0
          add: wireguard
          createInRoot: true
      bindNS:
          net: /run/netns/wg0
  - name: wg1
    image: linuxkit/ip:c88e3272e3b12edec454e4720da8bb70a7655bc7
    net: new
    binds:
      - /etc/wireguard:/etc/wireguard
    command: ["/usr/bin/lk-wg-config", "configure", "/etc/wireguard/wg1.conf"]
    runtime:
      interfaces:
        - name: wg1
          add: wireguard
          createInRoot: true
      bindNS:
          net: /run/netns/wg1
services:
  - name: getty
    image: linuxkit/getty:4fbbfb7d2e78c8da9be51fc93b78b96685fb1809
    env:
     - INSECURE=true
    net: /run/netns/wg1
  - name: rngd
    image: linuxkit/rngd:310c16ec5315bd07d4b8f5332cfa7dc5cbc7d368
  - name: nginx
    image: nginx:1.13.8-alpine
    net: /run/netns/wg0
    capabilities:
     - CAP_NET_BIND_SERVICE
     - CAP_CHOWN
     - CAP_SETUID
     - CAP_SETGID
     - CAP_DAC_OVERRIDE
files:
  - path: etc/wireguard/wg0.conf
    contents: |
      [Interface]
      Address = 192.168.2.1/24
      DNS = 192.168.2.2
      PrivateKey = KG7EKkHDkp7THfW5mOXcZzo3RbGAjq+ARMfJGFm5G1s=
      ListenPort = 51820
      [Peer] 
      PublicKey = ZP7h1OjA1oIAmsAvMKujp2RAAC/f0kY814b3Xq6j/0Y=
      AllowedIPs = 0.0.0.0/0
      Endpoint = 127.0.0.1:51821
  - path: etc/wireguard/wg1.conf
    contents: |
      [Interface]
      Address = 192.168.2.2/24
      PrivateKey = SCGCKDuTm4PMOw+LXdK/2s8mxnv145QHOohKRq3vc2A=
      ListenPort = 51821
      [Peer]
      PublicKey = AcS5t3PC5nL/oj0sYhc3yFpDlRaXoJ0mfEq6iq0rFF4=
      AllowedIPs = 0.0.0.0/0
      Endpoint = 127.0.0.1:51820
