kernel:
  image: linuxkit/kernel:5.10.104
  cmdline: "console=ttyS0 page_poison=1"
init:
  - linuxkit/init:31dcd928602e39ee752843ebcf6c35cbae73c883
  - linuxkit/runc:7ecf2e5253905855fb554b072d42903f7829c8b6
  - linuxkit/containerd:f645aa2f8aa58023149d7766725039572a2ebeb5
  - linuxkit/ca-certificates:4ed09a382de2b3ba2143f4270375b3bd6e973fb5
onboot:
  - name: sysctl
    image: linuxkit/sysctl:2f575c3d127824eb8d059673c538c440d22f19f5
  - name: sysfs
    image: linuxkit/sysfs:f383bf1c1094383fa3a42e5d5cba7d247dfc6720
  - name: dhcpcd
    image: linuxkit/dhcpcd:0cca76e71466fc6128fad585549b70538855f254
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: format
    image: linuxkit/format:ae6114d970492747fafbd2071602090c8df3bbf4
  - name: mount
    image: linuxkit/mount:6c799d9cd854cb13cab253945aa3893995f22704
    command: ["/usr/bin/mountie", "/var/lib/docker"]
services:
  - name: getty
    image: linuxkit/getty:ccac1189f78ff466b76d097a0b7b7236ea54de84
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:fffdd86f314fd960235adf3fba0587d2266d7a0f
  - name: ntpd
    image: linuxkit/openntpd:30314674e138726b6dc774dfb62a060d3a8da8d0
  - name: docker
    image: docker:20.10.6-dind
    capabilities:
     - all
    net: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
     - /var/lib/docker:/var/lib/docker
     - /lib/modules:/lib/modules
     - /var/run:/var/run
     - /etc/html:/var/html
    command: ["/usr/local/bin/docker-init", "/usr/local/bin/dockerd"]
  - name: compose
    image: linuxkitprojects/compose:111f9f32a933c9e7acbf3ccfc13fedbdfce8224f
    binds:
     - /var/run:/var/run
     - /etc/compose:/compose
files:
  - path: var/lib/docker
    directory: true
  - path: etc/html/a/index.html
    source: html-a.html
  - path: etc/html/b/index.html
    source: html-b.html
  - path: etc/compose/docker-compose.yml
    source: docker-compose.yml
  - path: etc/compose/images/nginx:alpine.tar
    source: image-cache/nginx:alpine.tar
  - path: etc/compose/images/traefik.tar
    source: image-cache/traefik.tar
trust:
  org:
    - linuxkit
    - library
