name: Release a tag

on:
  workflow_run:
    workflows: [LinuxKit CI]
    types: [completed]
    branches: [master, main]

jobs:
  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/pkg-v')
    name: Release packages
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.21
      uses: actions/setup-go@v3
      with:
        go-version: 1.21.5
      id: go
    - name: Check out code
      uses: actions/checkout@v3
    - name: Ensure bin/ directory
      run: mkdir -p bin
    - name: Download linuxkit
      run:
        go build -o bin/linuxkit ./src/cmd/linuxkit
        sudo mv bin/linuxkit /usr/local/bin/
    - name: Restore Package Cache
      uses: actions/cache@v3
      with:
        path: ~/.linuxkit/cache/
        key: ${{ runner.os }}-linuxkit-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-linuxkit-
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Publish Packages as Release
      run: |
        RELEASE_TAG=${GITHUB_REF#refs/tags/pkg-}
        echo "RELEASE_TAG=${RELEASE_TAG}"
        [ -n "${RELEASE_TAG}" ] || { echo "Not a tag"; exit 1; }
        make OPTIONS="--skip-platforms linux/s390x" -C pkg push PUSHOPTIONS="--nobuild --release ${RELEASE_TAG}"
